name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - readme
    paths:
      - .github/workflows/ci.yml

jobs:
  build:
    name: Build ${{ matrix.RELEASE }}-${{ matrix.BRANCH }}-${{ matrix.TYPE == 'desktop' && matrix.DESKTOP_ENVIRONMENT || matrix.TYPE }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        BRANCH:
          - edge
          - current
          - legacy
        RELEASE:
          - focal # Ubuntu 20.04 LTS
          - jammy # Ubuntu 22.04 LTS
          - bullseye # Debian 11
        TYPE:
          - minimal
          - cli
          - desktop
        exclude:
          - BRANCH: current
            TYPE: desktop
          - BRANCH: legacy
            TYPE: desktop
        include:
          - TYPE: desktop
            DESKTOP_ENVIRONMENT: xfce
            DESKTOP_ENVIRONMENT_CONFIG_NAME: config_base
            DESKTOP_APPGROUPS_SELECTED: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: armbian/build

      - name: Build
        run: |
          sudo ./compile.sh \
            BOARD=onecloud \
            BRANCH=${{ matrix.BRANCH }} \
            RELEASE=${{ matrix.RELEASE }} \
            KERNEL_CONFIGURE=no \
            KERNEL_ONLY=no \
            BUILD_MINIMAL=${{ matrix.TYPE == 'minimal' && 'yes' || 'no' }} \
            BUILD_DESKTOP=${{ matrix.TYPE == 'desktop' && 'yes' || 'no' }} \
            DESKTOP_ENVIRONMENT=${{ matrix.DESKTOP_ENVIRONMENT }} \
            DESKTOP_ENVIRONMENT_CONFIG_NAME=${{ matrix.DESKTOP_ENVIRONMENT_CONFIG_NAME }} \
            DESKTOP_APPGROUPS_SELECTED=${{ matrix.DESKTOP_APPGROUPS_SELECTED }} \
            EXPERT=yes \
            USE_CCACHE=no \
            NO_APT_CACHER=yes \
            COMPRESS_OUTPUTIMAGE=xz,sha,gpg

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.RELEASE }}-${{ matrix.BRANCH }}-${{ matrix.TYPE == 'desktop' && matrix.DESKTOP_ENVIRONMENT || matrix.TYPE }}
          path: output/images/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts/

      - name: Generate sha256sum
        run: |
          touch sha256sum
          for a in artifacts/*/*.sha; do
            cat "$a" >>sha256sum
            rm -f "$a"
          done

      - name: Show sha256sum
        run: |
          cat sha256sum

      - name: Release
        run: |
          time="${{ github.event.head_commit.timestamp }}"
          sha="${GITHUB_SHA:0:8}"
          tag="ci-$(date +'%Y%m%d-%H%M' -d "$time")"
          message="CI $(date +'%Y-%m-%d %H:%M' -d "$time")"
          hub release create  -t "$GITHUB_SHA" "$tag" -m "$message" \
            $(for a in artifacts/*/*; do echo -a $a; done) \
            -a sha256sum
        env:
          GITHUB_TOKEN: ${{ github.token }}
